$schema: https://json-schema.org/draft/2020-12/schema

$defs:
  languageStringSingle:
    oneOf:
      - type: string
      - type: object
        patternProperties:
          '^([A-Za-z]{1,8}(-[A-Za-z0-9]{1,8})*)?$':
            type: string
        additionalProperties: false

  languageStringArrayObject:
    type: object
    patternProperties:
      '^([A-Za-z]{1,8}(-[A-Za-z0-9]{1,8})*)?$':
        oneOf:
          - type: string
          - type: array
            items:
              type: string
    additionalProperties: false

  languageStringMultiple:
    oneOf:
      - $ref: '#/$defs/languageStringArrayObject'
      - type: array
        items:
          type: string

  typedValue:
    oneOf:
      - type: string
      - type: object
        required:
          - '@value'
        properties:
          '@value':
            type: string
          '@type':
            type: string

type: object
properties:
  id:
    $ref: bblocks://ogc.ogc-utils.iri-or-curie

  skosType:
    enum: [Concept, ConceptScheme, Collection, OrderedCollection]

  prefLabel:
    $ref: '#/$defs/languageStringSingle'
  altLabel:
    $ref: '#/$defs/languageStringMultiple'
  hiddenLabel:
    $ref: '#/$defs/languageStringMultiple'

  notation:
    oneOf:
      - $ref: '#/$defs/typedValue'
      - type: array
        items:
          $ref: '#/$defs/typedValue'

  note:
    $ref: '#/$defs/languageStringMultiple'
  changeNote:
    $ref: '#/$defs/languageStringMultiple'
  definition:
    $ref: '#/$defs/languageStringMultiple'
  editorialNote:
    $ref: '#/$defs/languageStringMultiple'
  example:
    $ref: '#/$defs/languageStringMultiple'
  historyNote:
    $ref: '#/$defs/languageStringMultiple'
  scopeNote:
    $ref: '#/$defs/languageStringMultiple'